### PR TITLE
BACKLOG-22948: implement MultipleModuleVersions and MultipleBundleVersions probes

### PR DESCRIPTION
**Pull request by jkevan**

### CODE REVIEW

**Review by gflores-jahia — DISMISSED** [review]
This is totally personal opinion, but from code org perspective, I feel it makes it "cleaner" to have the bundle functions separated as a util class (including the duplicateinfo class) that both probes can call rather than adding hierarchy (extends) to MultipleBundleVersion. 

Makes the bundle functions a bit more reusable in the future if needed (but we can also do that refactor then)

**Comment by jkevan** [comment]
> This is totally personal opinion, but from code org perspective, I feel it makes it "cleaner" to have the bundle functions separated as a util class (including the duplicateinfo class) that both probes can call rather than adding hierarchy (extends) to MultipleBundleVersion.
> 
> Makes the bundle functions a bit more reusable in the future if needed (but we can also do that refactor then)

Thanks for the review !
Yes I hesitated between your proposition and the current implem. But since I introduced a new Object to represent the format of the duplicated data, it was not really obvious that this methods/classes would be useful to others probes.
Still hesitating RN, will see if I change my mind.

**Comment by gflores-jahia** [comment]
Understood. comment is very minor and doesn't affect functionality all, so I feel we can go either way for now.

**Review by TimRobertDev — APPROVED** [review]
Looks good to me !

**Pull request merged**
